CREATE TABLE IF NOT EXISTS TEACHERS (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(20),
  last_name VARCHAR(20),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USERS (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(50) UNIQUE,
  first_name VARCHAR(20),
  last_name VARCHAR(20),
  password VARCHAR(120),
  admin BOOLEAN NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SESSIONS (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  date TIMESTAMP NOT NULL,
  description VARCHAR(2500) NOT NULL,
  teacher_id BIGINT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  FOREIGN KEY (teacher_id) REFERENCES TEACHERS(id)
);

CREATE TABLE IF NOT EXISTS PARTICIPATE (
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (session_id, user_id),
  FOREIGN KEY (session_id) REFERENCES SESSIONS(id),
  FOREIGN KEY (user_id) REFERENCES USERS(id)
);